### ISSUE TITLE
runPostCrab: key error: 'lfn'

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/GridIn#75]
I just had this issue:

```
##### Check if the dataset exists in the database
calling das_import
****das query: [{u'dataset': [{u'name': u'/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM', u'datatype': u'mc', u'creation_time': u'2016-03-04 13:06:34', u'nevents': 2855237, u'tag': None, u'size': 66366967059}]}]
Dataset #None:
  name: /VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/MINIAODSIM
  process: VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8
  cross-section: 1.0
  number of events: 2855237
  size on disk: 66366967059
  CMSSW release: CMSSW_7_6_3
  global tag: 76X_mcRun2_asymptotic_v12
  type (data or mc): mc
  center-of-mass energy: 13.0 TeV
  creation time (on DAS): 2016-03-04 13:06:34
  comment: 
Insert into the database? [y]|n: y
done
done

##### Get info from crab (outputs, report)
done

##### Get information from the output files
Traceback (most recent call last):
  File "/nfs/scratch/fynu/swertz/CMSSW_7_6_3_patch2/bin/slc6_amd64_gcc493/runPostCrab.py", line 368, in <module>
    main() 
  File "/nfs/scratch/fynu/swertz/CMSSW_7_6_3_patch2/bin/slc6_amd64_gcc493/runPostCrab.py", line 278, in main
    for (i, lfn) in enumerate(output_files['lfn']):
KeyError: 'lfn'
##### Get information out of the crab config file (work area, dataset, pset)
done
```

The dataset is in the database: http://cp3.irmp.ucl.ac.be/~delaere/level2/SAMADhi/index.php?-action=view&-table=dataset&-cursor=14&-skip=0&-limit=30&-mode=find&-sort=creation_time+asc%2C+name+asc&-recordid=dataset%3Fdataset_id%3D270&-edit=1&cmssw_release=CMSSW_7_6_3
but there is no sample attached...

Out of 20 samples I've just added it's the only one which gave this error. There was nothing wrong with the crab tasks I've picked up...

**Comment by swertz** [comment]
It seems that I cannot read anymore: the jobs for this dataset were actually never submitted to the crab server => no output => this bug.
